

export enum subsidiaries {
    FSL_ASSET_MANAGEMENT = 'FSL_ASSET_MANAGEMENT',
    FSL_INSURANCE_BROKERS = 'FSL_INSURANCE_BROKERS', 
    FSL_MANAGEMENT_SERVICES = 'FSL_MANAGEMENT_SERVICES', 
    FSL_FINANCE = 'FSL_FINANCE', 
    FSL_REGISTRARS = 'FSL_REGISTRARS'
}

export const subSidiaryArray = ['FSL_ASSET_MANAGEMENT', 'FSL_INSURANCE_BROKERS', 'FSL_MANAGEMENT_SERVICES', 'FSL_FINANCE', 'FSL_REGISTRARS']